language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

# command to install dependencies
install: "pip install -Ur requirements.txt"

# command to run tests, e.g. python setup.py test
script: nosetests --with-cov --cov=xlwt

after_success:
  - coveralls
